#!/usr/bin/env python3.12
from app.exceptions import ApiServiceError
from app.ip_service import IPService, Ifconfig
from app.location_service import LocationService, Ipapi
from app.weather_service import WeatherService, VisualCrossing
from app.formatter import format_weather


def get_weather_info(
        ip_service: IPService,
        location_service: LocationService,
        weather_service: WeatherService) -> str:
    try:
        ip = ip_service.get_ip()
    except ApiServiceError:
        print("Can't get ip adress from ip service")
        exit(1)
    try:
        location = location_service.get_location(ip)
    except ApiServiceError:
        print("Can't get location from location service")
        exit(1)
    try:
        weather = weather_service.get_weather(location.coordinates)
    except ApiServiceError:
        print("Can't get weather information form weather service")
        exit(1)
    return format_weather(location, weather)


def main():
    ip_service = Ifconfig()
    location_service = Ipapi()
    weather_service = VisualCrossing()
    print(get_weather_info(ip_service, location_service, weather_service))


if __name__ == "__main__":
    main()
